"""
Extended package aliases - 500+ mappings for common software names.
Covers all major categories of software that users might want to install.
"""

EXTENDED_ALIASES_500 = {
    # ===== Web Browsers (20+) =====
    "chrome": "google-chrome",
    "chromium": "chromium",
    "firefox": "firefox",
    "brave": "brave",
    "opera": "opera",
    "vivaldi": "vivaldi",
    "edge": "microsoft-edge",
    "safari": "epiphany",  # GNOME Web as Safari alternative
    "tor": "tor-browser-bundle-bin",
    "lynx": "lynx",
    "w3m": "w3m",
    "qutebrowser": "qutebrowser",
    "midori": "midori",
    "falkon": "falkon",
    "pale moon": "palemoon-bin",
    "seamonkey": "seamonkey",
    "waterfox": "waterfox",
    "icecat": "icecat",
    "librewolf": "librewolf",
    "ungoogled-chromium": "ungoogled-chromium",
    # ===== Text Editors & IDEs (40+) =====
    "vscode": "vscode",
    "code": "vscode",
    "visual studio code": "vscode",
    "vscodium": "vscodium",
    "vim": "vim",
    "neovim": "neovim",
    "nvim": "neovim",
    "emacs": "emacs",
    "spacemacs": "emacs",
    "doom emacs": "emacs",
    "sublime": "sublime4",
    "sublime text": "sublime4",
    "atom": "atom",
    "brackets": "brackets",
    "gedit": "gedit",
    "kate": "kate",
    "nano": "nano",
    "micro": "micro",
    "helix": "helix",
    "kakoune": "kakoune",
    "xi": "xi-editor",
    "amp": "amp",
    "ne": "ne",
    "joe": "joe",
    "jed": "jed",
    "leafpad": "leafpad",
    "mousepad": "mousepad",
    "pluma": "pluma",
    "geany": "geany",
    "bluefish": "bluefish",
    "eclipse": "eclipse",
    "intellij": "jetbrains.idea-community",
    "idea": "jetbrains.idea-community",
    "pycharm": "jetbrains.pycharm-community",
    "webstorm": "jetbrains.webstorm",
    "phpstorm": "jetbrains.phpstorm",
    "rubymine": "jetbrains.ruby-mine",
    "goland": "jetbrains.goland",
    "clion": "jetbrains.clion",
    "android studio": "android-studio",
    # ===== Terminal Emulators (25+) =====
    "terminal": "gnome-terminal",
    "gnome-terminal": "gnome-terminal",
    "konsole": "konsole",
    "xterm": "xterm",
    "urxvt": "rxvt-unicode",
    "rxvt": "rxvt-unicode",
    "alacritty": "alacritty",
    "kitty": "kitty",
    "terminator": "terminator",
    "tilix": "tilix",
    "hyper": "hyper",
    "termite": "termite",
    "st": "st",
    "cool-retro-term": "cool-retro-term",
    "guake": "guake",
    "tilda": "tilda",
    "yakuake": "yakuake",
    "terminology": "terminology",
    "sakura": "sakura",
    "roxterm": "roxterm",
    "lxterminal": "lxterminal",
    "xfce4-terminal": "xfce4-terminal",
    "mate-terminal": "mate-terminal",
    "foot": "foot",
    "wezterm": "wezterm",
    # ===== Development Tools (50+) =====
    "git": "git",
    "github": "gh",
    "gh": "gh",
    "gitlab": "gitlab",
    "svn": "subversion",
    "subversion": "subversion",
    "mercurial": "mercurial",
    "hg": "mercurial",
    "fossil": "fossil",
    "cvs": "cvs",
    "make": "gnumake",
    "cmake": "cmake",
    "ninja": "ninja",
    "meson": "meson",
    "autotools": "autoconf",
    "automake": "automake",
    "gcc": "gcc",
    "g++": "gcc",
    "clang": "clang",
    "llvm": "llvm",
    "rust": "rustc",
    "rustc": "rustc",
    "cargo": "cargo",
    "go": "go",
    "golang": "go",
    "python": "python3",
    "python3": "python3",
    "python2": "python2",
    "pip": "python3Packages.pip",
    "node": "nodejs",
    "nodejs": "nodejs",
    "npm": "nodejs",
    "yarn": "yarn",
    "pnpm": "pnpm",
    "deno": "deno",
    "ruby": "ruby",
    "rails": "rubyPackages.rails",
    "java": "jdk",
    "jdk": "jdk",
    "jre": "jre",
    "maven": "maven",
    "gradle": "gradle",
    "ant": "ant",
    "scala": "scala",
    "sbt": "sbt",
    "kotlin": "kotlin",
    "groovy": "groovy",
    "perl": "perl",
    "php": "php",
    "composer": "phpPackages.composer",
    "lua": "lua",
    "julia": "julia",
    "r": "R",
    "octave": "octave",
    # ===== Databases (30+) =====
    "mysql": "mysql",
    "mariadb": "mariadb",
    "postgres": "postgresql",
    "postgresql": "postgresql",
    "sqlite": "sqlite",
    "sqlite3": "sqlite",
    "mongodb": "mongodb",
    "mongo": "mongodb",
    "redis": "redis",
    "cassandra": "cassandra",
    "couchdb": "couchdb",
    "elasticsearch": "elasticsearch",
    "neo4j": "neo4j",
    "influxdb": "influxdb",
    "prometheus": "prometheus",
    "grafana": "grafana",
    "memcached": "memcached",
    "rabbitmq": "rabbitmq-server",
    "kafka": "apacheKafka",
    "dynamodb": "dynamodb-local",
    "firebird": "firebird",
    "orientdb": "orientdb",
    "arangodb": "arangodb",
    "rethinkdb": "rethinkdb",
    "cockroachdb": "cockroachdb",
    "timescaledb": "timescaledb",
    "clickhouse": "clickhouse",
    "questdb": "questdb",
    "duckdb": "duckdb",
    "rocksdb": "rocksdb",
    # ===== Cloud & DevOps (40+) =====
    "docker": "docker",
    "docker-compose": "docker-compose",
    "podman": "podman",
    "kubernetes": "kubernetes",
    "k8s": "kubernetes",
    "kubectl": "kubectl",
    "minikube": "minikube",
    "k3s": "k3s",
    "k9s": "k9s",
    "helm": "kubernetes-helm",
    "terraform": "terraform",
    "ansible": "ansible",
    "puppet": "puppet",
    "chef": "chef",
    "salt": "salt",
    "vagrant": "vagrant",
    "packer": "packer",
    "consul": "consul",
    "vault": "vault",
    "nomad": "nomad",
    "jenkins": "jenkins",
    "gitlab-runner": "gitlab-runner",
    "github-actions": "act",
    "circleci": "circleci-cli",
    "travis": "travis",
    "aws": "awscli2",
    "aws-cli": "awscli2",
    "gcloud": "google-cloud-sdk",
    "azure": "azure-cli",
    "digitalocean": "doctl",
    "linode": "linode-cli",
    "heroku": "heroku",
    "fly": "flyctl",
    "serverless": "serverless",
    "localstack": "localstack",
    "minio": "minio",
    "s3cmd": "s3cmd",
    "rclone": "rclone",
    "restic": "restic",
    "borg": "borgbackup",
    # ===== Media Players (25+) =====
    "vlc": "vlc",
    "mpv": "mpv",
    "mplayer": "mplayer",
    "smplayer": "smplayer",
    "kodi": "kodi",
    "plex": "plex",
    "jellyfin": "jellyfin",
    "emby": "emby",
    "spotify": "spotify",
    "rhythmbox": "rhythmbox",
    "amarok": "amarok",
    "clementine": "clementine",
    "strawberry": "strawberry",
    "audacious": "audacious",
    "banshee": "banshee",
    "deadbeef": "deadbeef",
    "cmus": "cmus",
    "mpd": "mpd",
    "ncmpcpp": "ncmpcpp",
    "moc": "moc",
    "sox": "sox",
    "ffmpeg": "ffmpeg",
    "handbrake": "handbrake",
    "obs": "obs-studio",
    "kdenlive": "kdenlive",
    # ===== Graphics & Design (30+) =====
    "gimp": "gimp",
    "photoshop": "gimp",  # Alternative
    "inkscape": "inkscape",
    "illustrator": "inkscape",  # Alternative
    "krita": "krita",
    "blender": "blender",
    "freecad": "freecad",
    "openscad": "openscad",
    "librecad": "librecad",
    "darktable": "darktable",
    "rawtherapee": "rawtherapee",
    "digikam": "digikam",
    "shotwell": "shotwell",
    "gthumb": "gthumb",
    "imagemagick": "imagemagick",
    "graphicsmagick": "graphicsmagick",
    "scribus": "scribus",
    "mypaint": "mypaint",
    "pinta": "pinta",
    "xfig": "xfig",
    "dia": "dia",
    "draw.io": "drawio",
    "pencil": "pencil",
    "gravit": "gravit-designer",
    "figma": "figma-linux",
    "aseprite": "aseprite",
    "godot": "godot",
    "unity": "unityhub",
    "unreal": "unrealengine",
    "love2d": "love",
    # ===== Office & Productivity (25+) =====
    "libreoffice": "libreoffice",
    "office": "libreoffice",
    "word": "libreoffice",
    "excel": "libreoffice",
    "powerpoint": "libreoffice",
    "openoffice": "openoffice",
    "onlyoffice": "onlyoffice-bin",
    "calligra": "calligra",
    "abiword": "abiword",
    "gnumeric": "gnumeric",
    "latex": "texlive.combined.scheme-full",
    "tex": "texlive.combined.scheme-full",
    "pandoc": "pandoc",
    "markdown": "pandoc",
    "zotero": "zotero",
    "mendeley": "mendeley",
    "calibre": "calibre",
    "evince": "evince",
    "okular": "okular",
    "zathura": "zathura",
    "mupdf": "mupdf",
    "xournal": "xournalpp",
    "remarkable": "remarkable",
    "obsidian": "obsidian",
    "notion": "notion-app-enhanced",
    # ===== Communication (30+) =====
    "slack": "slack",
    "discord": "discord",
    "teams": "teams",
    "zoom": "zoom-us",
    "skype": "skypeforlinux",
    "telegram": "telegram-desktop",
    "signal": "signal-desktop",
    "whatsapp": "whatsapp-for-linux",
    "element": "element-desktop",
    "riot": "element-desktop",
    "matrix": "element-desktop",
    "irc": "hexchat",
    "hexchat": "hexchat",
    "irssi": "irssi",
    "weechat": "weechat",
    "pidgin": "pidgin",
    "empathy": "empathy",
    "thunderbird": "thunderbird",
    "evolution": "evolution",
    "geary": "geary",
    "kmail": "kmail",
    "mutt": "mutt",
    "neomutt": "neomutt",
    "aerc": "aerc",
    "alpine": "alpine",
    "mailspring": "mailspring",
    "birdtray": "birdtray",
    "rambox": "rambox",
    "franz": "franz",
    "ferdi": "ferdi",
    # ===== System Tools (40+) =====
    "htop": "htop",
    "btop": "btop",
    "gotop": "gotop",
    "glances": "glances",
    "iotop": "iotop",
    "iftop": "iftop",
    "nethogs": "nethogs",
    "ncdu": "ncdu",
    "dust": "dust",
    "duf": "duf",
    "tree": "tree",
    "exa": "exa",
    "lsd": "lsd",
    "bat": "bat",
    "fd": "fd",
    "find": "findutils",
    "fzf": "fzf",
    "ripgrep": "ripgrep",
    "rg": "ripgrep",
    "ag": "silver-searcher",
    "ack": "ack",
    "tmux": "tmux",
    "screen": "screen",
    "zsh": "zsh",
    "fish": "fish",
    "bash": "bash",
    "oh-my-zsh": "oh-my-zsh",
    "starship": "starship",
    "powerline": "powerline-go",
    "neofetch": "neofetch",
    "screenfetch": "screenfetch",
    "pfetch": "pfetch",
    "ranger": "ranger",
    "nnn": "nnn",
    "mc": "mc",
    "midnight commander": "mc",
    "vifm": "vifm",
    "lf": "lf",
    "broot": "broot",
    # ===== Security Tools (25+) =====
    "nmap": "nmap",
    "wireshark": "wireshark",
    "tcpdump": "tcpdump",
    "metasploit": "metasploit",
    "burpsuite": "burpsuite",
    "john": "john",
    "hashcat": "hashcat",
    "aircrack": "aircrack-ng",
    "hydra": "hydra",
    "sqlmap": "sqlmap",
    "nikto": "nikto",
    "dirb": "dirb",
    "gobuster": "gobuster",
    "ffuf": "ffuf",
    "masscan": "masscan",
    "zap": "zap",
    "openvas": "openvas-scanner",
    "lynis": "lynis",
    "chkrootkit": "chkrootkit",
    "rkhunter": "rkhunter",
    "clamav": "clamav",
    "fail2ban": "fail2ban",
    "ufw": "ufw",
    "iptables": "iptables",
    "gpg": "gnupg",
    # ===== Gaming (20+) =====
    "steam": "steam",
    "lutris": "lutris",
    "wine": "wine",
    "proton": "proton-caller",
    "playonlinux": "playonlinux",
    "retroarch": "retroarch",
    "dolphin": "dolphin-emu",
    "pcsx2": "pcsx2",
    "rpcs3": "rpcs3",
    "yuzu": "yuzu-mainline",
    "cemu": "cemu",
    "mame": "mame",
    "dosbox": "dosbox",
    "scummvm": "scummvm",
    "minecraft": "minecraft",
    "multimc": "multimc",
    "heroic": "heroic",
    "bottles": "bottles",
    "gamehub": "gamehub",
    "gamemode": "gamemode",
    # ===== Network Tools (20+) =====
    "curl": "curl",
    "wget": "wget",
    "aria2": "aria2",
    "httpie": "httpie",
    "postman": "postman",
    "insomnia": "insomnia",
    "netcat": "netcat",
    "nc": "netcat",
    "socat": "socat",
    "telnet": "telnet",
    "ssh": "openssh",
    "mosh": "mosh",
    "rsync": "rsync",
    "scp": "openssh",
    "sftp": "openssh",
    "filezilla": "filezilla",
    "transmission": "transmission",
    "qbittorrent": "qbittorrent",
    "deluge": "deluge",
    "rtorrent": "rtorrent",
    # ===== File Managers (15+) =====
    "nautilus": "gnome.nautilus",
    "dolphin": "dolphin",
    "thunar": "xfce.thunar",
    "pcmanfm": "pcmanfm",
    "nemo": "cinnamon.nemo",
    "caja": "mate.caja",
    "spacefm": "spacefm",
    "doublecmd": "doublecmd",
    "krusader": "krusader",
    "xfe": "xfe",
    "rox": "rox-filer",
    "worker": "worker",
    "gentoo": "gentoo",
    "tuxcmd": "tuxcmd",
    "sunflower": "sunflower",
    # ===== Scientific & Math (15+) =====
    "matlab": "octave",  # Alternative
    "mathematica": "sage",  # Alternative
    "scipy": "python3Packages.scipy",
    "numpy": "python3Packages.numpy",
    "pandas": "python3Packages.pandas",
    "jupyter": "jupyter",
    "jupyterlab": "jupyterlab",
    "rstudio": "rstudio",
    "spyder": "spyder",
    "gnuplot": "gnuplot",
    "maxima": "maxima",
    "scilab": "scilab",
    "geogebra": "geogebra",
    "stellarium": "stellarium",
    "celestia": "celestia",
    # ===== Backup & Sync (15+) =====
    "dropbox": "dropbox",
    "nextcloud": "nextcloud-client",
    "owncloud": "owncloud-client",
    "syncthing": "syncthing",
    "seafile": "seafile-client",
    "duplicati": "duplicati",
    "duplicity": "duplicity",
    "deja-dup": "deja-dup",
    "backintime": "backintime",
    "timeshift": "timeshift",
    "rsnapshot": "rsnapshot",
    "rdiff-backup": "rdiff-backup",
    "bacula": "bacula",
    "amanda": "amanda",
    "tarsnap": "tarsnap",
    # ===== Virtualization (15+) =====
    "virtualbox": "virtualbox",
    "vbox": "virtualbox",
    "vmware": "vmware-workstation",
    "qemu": "qemu",
    "kvm": "qemu_kvm",
    "virt-manager": "virt-manager",
    "gnome-boxes": "gnome.gnome-boxes",
    "xen": "xen",
    "bhyve": "bhyve",
    "lxc": "lxc",
    "lxd": "lxd",
    "multipass": "multipass",
    "parallels": "parallels",
    "utm": "utm",
    "lima": "lima",
    "firecracker": "firecracker",
    # ===== Password Managers (10+) =====
    "bitwarden": "bitwarden",
    "1password": "_1password-gui",
    "keepass": "keepass",
    "keepassxc": "keepassxc",
    "pass": "pass",
    "gopass": "gopass",
    "lastpass": "lastpass-cli",
    "dashlane": "dashlane",
    "enpass": "enpass",
    "buttercup": "buttercup-desktop",
    # ===== Shells & Terminal Tools (10+) =====
    "zellij": "zellij",
    "warp": "warp-terminal",
    "fig": "fig",
    "asciinema": "asciinema",
    "ttyd": "ttyd",
    "tmate": "tmate",
    "byobu": "byobu",
    "dvtm": "dvtm",
    "abduco": "abduco",
    "dtach": "dtach",
}

# Category mappings for browsing
CATEGORIES = {
    "browsers": ["chrome", "firefox", "brave", "opera", "vivaldi", "edge", "tor"],
    "editors": ["vscode", "vim", "neovim", "emacs", "sublime", "atom", "helix"],
    "development": ["git", "docker", "python", "node", "rust", "go", "java"],
    "databases": ["mysql", "postgres", "mongodb", "redis", "sqlite", "cassandra"],
    "cloud": ["kubernetes", "terraform", "ansible", "aws", "gcloud", "azure"],
    "media": ["vlc", "mpv", "spotify", "obs", "ffmpeg", "handbrake"],
    "graphics": ["gimp", "inkscape", "krita", "blender", "darktable"],
    "office": ["libreoffice", "latex", "pandoc", "obsidian", "notion"],
    "communication": ["slack", "discord", "teams", "zoom", "telegram", "signal"],
    "security": ["nmap", "wireshark", "metasploit", "burpsuite", "clamav"],
    "gaming": ["steam", "lutris", "wine", "retroarch", "minecraft"],
    "system": ["htop", "tmux", "zsh", "docker", "git", "ranger"],
}


def get_package_name(alias: str) -> str:
    """Get the actual package name from an alias."""
    return EXTENDED_ALIASES_500.get(alias.lower(), alias)


def search_packages(query: str) -> list:
    """Search for packages matching a query."""
    query_lower = query.lower()
    results = []

    for alias, package in EXTENDED_ALIASES_500.items():
        if query_lower in alias or query_lower in package:
            results.append({"alias": alias, "package": package})

    return results


def get_category_packages(category: str) -> list:
    """Get all packages in a category."""
    if category in CATEGORIES:
        return [EXTENDED_ALIASES_500.get(pkg, pkg) for pkg in CATEGORIES[category]]
    return []


# Export count for verification
TOTAL_ALIASES = len(EXTENDED_ALIASES_500)
print(f"Loaded {TOTAL_ALIASES} package aliases")
